services:
  rabbitexample:
    image: ${DOCKER_REGISTRY-}rabbitexample
    build:
      context: .
      dockerfile: Rabbit example/Dockerfile

  consumerservice:
    image: ${DOCKER_REGISTRY-}consumerservice
    build:
      context: .
      dockerfile: ConsumerService/Dockerfile

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

