services:
  consoleapp1:
    image: ${DOCKER_REGISTRY-}consoleapp1
    build:
      context: .
      dockerfile: ConsoleApp1/Dockerfile

  consoleapp2:
    image: ${DOCKER_REGISTRY-}consoleapp2
    build:
      context: .
      dockerfile: ConsoleApp2/Dockerfile

